import Cookies from "js-cookie";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button } from "~/components/ui/button";

export default function Home() {
  const router = useRouter();
  const logout = () => {
    Cookies.set("authToken", "");
    router.push("/login");
  };
  return (
    <>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div className="bg-slate-500 p-4 rounded-xl mt-5 flex justify-between items-center">
            <h1 className="text-3xl font-bold text-white">
              Hello {localStorage.getItem("name")}
            </h1>
            <Button
              className="bg-red-500 text-white rounded-xl hover:bg-red-700"
              onClick={logout}
            >
              logout
            </Button>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const isAuthenticated = !!context.req.cookies.authToken;

  if (!isAuthenticated) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
